wordfilter.wordfilter_configuration.*:
  type: config_entity
  label: 'Wordfilter configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    process_id:
      type: string
      label: 'Filtering process'
    items:
      type: sequence
      label: 'Filtering items'
      sequence:
        type: mapping
        label: 'Filtering item'
        mapping:
          delta:
            type: integer
            label: 'Item delta (position)'
          substitute:
            type: text
            label: 'Substitution text'
          filter_words:
            type: text
            label: 'Words to filter'

filter_settings.wordfilter:
  type: filter
  label: 'Wordfilter'
  mapping:
    active_wordfilter_configs:
      type: sequence
      label: 'Active Wordfilter configurations'
      sequence:
        type: string
        label: 'Wordfilter configuration'

node.type.*.third_party.wordfilter:
  type: mapping
  label: 'Wordfilter'
  mapping:
    active_wordfilter_configs:
      type: sequence
      label: 'Active wordfilter configurations'
      sequence:
        type: string
        label: 'Wordfilter configuration'

comment.type.*.third_party.wordfilter:
  type: mapping
  label: 'Wordfilter'
  mapping:
    active_wordfilter_configs:
      type: sequence
      label: 'Active wordfilter configurations'
      sequence:
        type: string
        label: 'Wordfilter configuration'
